### ISSUE TITLE
how to delete any element 

### ISSUE THREAD

**Issue by MhmedRjb** [frappe/print_designer#334]

**Comment by MhmedRjb** [comment]
Okay, I just realized that to delete an element, you need to open the layers and click the delete button.

**Comment by bibinqcs** [comment]
Hi, how did you get the delete button?

**Comment by naga-mantha** [comment]
Where is the delete button? I dont see anywhere? Screenshot please, if possible.

**Comment by MhmedRjb** [comment]
@naga-mantha I was referring to the 'Delete' key on the keyboard.
click it after open layers

**Comment by naga-mantha** [comment]
I tried that, didnt work. I installed Unbuntu on Virtual box and using firefox, if that helps.

When I open the layers, I see a list, but when I click on any element on the list, its not even clickable.

**Comment by MhmedRjb** [comment]
After open the layers, click on the element directly on the page, not in the layers panel. like this 
![test10](https://github.com/user-attachments/assets/bdb29049-480a-498a-9de4-8c561ee8b312)

**Comment by naga-mantha** [comment]
Nope not working. I think its the browser or the VM itself. Will figure it out.

**Comment by MhmedRjb** [comment]
@naga-mantha
Good luck; I use Google Chrome and Ubuntu

**Comment by maharshivpatel** [comment]
@naga-mantha @MhmedRjb it was bug which was introduced in some recent refactor i have fixed it. please check and let me know if it works in develop version / v1.4.2

**Comment by naga-mantha** [comment]
I installed v1.4.1 and deleting worked. But in v1.4.2 the delete doesn't work.

Additionally for me, I am not even able to drag the elements (in both versions).. Maybe its an error in my virtual box/Ubuntu?

**Comment by MhmedRjb** [comment]
@maharshivpatel I have updated to the latest version, but the delete still not working, whether the layers panel is open or not.
Additionally, when I try to edit an old print format, it keeps loading indefinitely. I tested this in both Chrome and Edge browsers, in case that information is helpful.

**Comment by naga-mantha** [comment]
Try v1.4.1.

**Comment by edardev** [comment]
The issue persists while using the "develop" branch for a custom Docker image. I'm unable to delete with the 'Backspace' key, and the Layers tab won't allow me to delete elements either.
